CREATE TABLE IF NOT EXISTS `sync_jobs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `job_name` VARCHAR(120) NOT NULL,
  `trigger_time` DATETIME NOT NULL,
  `run_type` VARCHAR(30) NOT NULL DEFAULT 'manual',
  `status` VARCHAR(30) NOT NULL DEFAULT 'pending',
  `started_at` DATETIME NULL,
  `finished_at` DATETIME NULL,
  `estimated_seconds` INT NULL,
  `actual_seconds` INT NULL,
  `total_tasks` INT NOT NULL DEFAULT 0,
  `completed_tasks` INT NOT NULL DEFAULT 0,
  `current_step` VARCHAR(60) NULL,
  `current_target` VARCHAR(120) NULL,
  `fetched_count` INT NOT NULL DEFAULT 0,
  `inserted_count` INT NOT NULL DEFAULT 0,
  `skipped_count` INT NOT NULL DEFAULT 0,
  `deleted_count` INT NOT NULL DEFAULT 0,
  `message` TEXT NULL,
  `target_areas` JSON NULL,
  `target_sources` JSON NULL,
  `triggered_by_user_id` BIGINT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sync_job_details` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `job_id` BIGINT NOT NULL,
  `area_label` VARCHAR(60) NOT NULL,
  `source_product` VARCHAR(60) NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'pending',
  `step` VARCHAR(60) NULL,
  `started_at` DATETIME NULL,
  `finished_at` DATETIME NULL,
  `fetched_count` INT NOT NULL DEFAULT 0,
  `inserted_count` INT NOT NULL DEFAULT 0,
  `skipped_count` INT NOT NULL DEFAULT 0,
  `deleted_count` INT NOT NULL DEFAULT 0,
  `message` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
